spring:
  application:
    name: comments-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

issuer:
  uri: http://localhost:7080/realms/master

server:
  port: 7000
  servlet:
    context-path: /api/v1/comment-service

backend:
  uri: https://jsonplaceholder.typicode.com/comments